"""Garage table

Revision ID: 367413a79e89
Revises: 1696b6624794
Create Date: 2023-09-07 00:25:56.267732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367413a79e89'
down_revision = '1696b6624794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garages', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('garages', 'location')
    # ### end Alembic commands ###
